### ISSUE TITLE
Not supported valid fluentbit configurations with duplicated keys

### ISSUE THREAD

**Issue by ricsanfre** [ricsanfre/ansible-role-fluentbit#2]
Current implementation defines fluentbit configuration using a yaml variables (list of dictionaries) that are translated to a valid fluentbit configuration file using jinja2 template

```yml
fluentbit_filters:
  - Name: kubernetes
    Match: kube.*
    Kube_Tag_Prefix: kube.var.log.containers.
    Merge_Log: true
    Merge_Log_Trim: true
    Keep_Log: false
    K8S-Logging.Parser: true
    K8S-Logging.Exclude: false
    Annotations: false
    Labels: true
```
In this data structure dictionary's key cannot be repeated and, so FILTER definitions with repeated operations (like the defined below with multiple Rename or Remove statements within the same filter)  are not allowed.

```
[FILTER]
    Name modify
    Match kube.*
    Rename kubernetes_pod_name k8s.pod.name
    Rename kubernetes_namespace_name k8s.namespace.name
    Rename kubernetes_container_name k8s.container.name
    Remove kubernetes_container_image
    Remove kubernetes_docker_id
    Remove kubernetes_pod_id
    Remove kubernetes_host
    Remove kubernetes_container_hash
    Remove stream
    Remove _p
    Rename log message
    Add k8s.cluster.name picluster
```

Implementation must be changed to support this valid fluentbit configuration. Instead of using YAML's list of dictionaries variables use string YAML variables with the actual content of each of the configuration file section ([SERVER], [FILTER], [OUTPUT]), etc
